sudo: false
language: node_js
node_js:
  - "11.10.1"
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - npm test -- -u
after_success:
  - npm run coveralls
notifications:
  email: false
  slack: andela:2g4OM4yEbPLKguWbH6jcTkIU#ah-kgl-wakanda
