export const PUBLISH_ARTICLE = 'PUBLISH_ARTICLE';
export const GET_SINGLE_ARTICLE = 'GET_SINGLE_ARTICLE';
export const DELETE_SINGLE_ARTICLE = 'DELETE_SINGLE_ARTICLE';
export const LOAD = 'LOAD';
export const STOP_LOADING = 'STOP_LOADING';
export const DISPLAY_COMMENTS = 'DISPLAY_COMMENTS';
