export const BOOKMARK = 'BOOKMARK';
export const BOOKMARK_STARTED = 'BOOKMARK_STARTED';
export const BOOKMARK_SUCCESS = 'BOOKMARK_SUCCESS';
export const BOOKMARK_ERROR = 'BOOKMARK_ERROR';
export const UNBOOKMARK = 'UNBOOKMARK';
export const UNBOOKMARK_STARTED = 'UNBOOKMARK_STARTED';
export const UNBOOKMARK_SUCCESS = 'UNBOOKMARK_SUCCESS';
export const UNBOOKMARK_ERROR = 'UNBOOKMARK_ERROR';
