export const FETCH_ARTICLES_STARTED = 'FETCH_ARTICLES_STARTED';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';
export const FETCH_USER_ARTICLES = 'FETCH_USER_ARTICLES';
export const NEW_FEED = 'NEW_FEED';
export const NEW_USER_ARTICLES = 'NEW_USER_ARTICLES';
