export const CHANGE_NAME = 'CHANGE_NAME';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SEND = 'RESET_PASSWORD_SEND';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SEND = 'UPDATE_PASSWORD_SEND';
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR';
export const TOGGLE_SIDE_NAV = 'TOGGLE_SIDE_NAV';
